name: Slack Notification

on:
  create:
    tags: 
      - 'refs/tags/website-us-*'
    branches:
      - 'releaseus/**'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Latest Tag
        id: tag
        run: |
          latest_tag=$(git tag -l "website-us-*" --sort=-v:refname | head -n 1)
          echo "::set-output name=tag::$latest_tag"

      - name: Send Slack Notification
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: |
          latest_tag_link = "https://github.com/${{ github.repository }}/releases/tag/${{ steps.tag.outputs.tag }}"
          branch_name=$(git rev-parse --symbolic --abbrev-ref ${{ github.ref }})
          payload="{
            \"channel\": \"#test1\",
            \"text\": \"New tag created: [${{ steps.tag.outputs.tag }}](${latest_tag_link})\",
            \"username\": \"GitHub Actions\",
            \"icon_emoji\": \":rocket:\"
          }"
          curl -X POST -H "Content-type: application/json" -H "Authorization: Bearer $SLACK_TOKEN" --data "$payload" https://slack.com/api/chat.postMessage
